### ISSUE TITLE
他人详情楼宇信息显示不全

### ISSUE THREAD

**Issue by rexpie** [rexpie/catchup-gui#12]
![image](https://cloud.githubusercontent.com/assets/6948474/5377744/d13ea9ac-80bf-11e4-9a85-622fb23dea80.png)
似乎autolayout也没有？
![image](https://cloud.githubusercontent.com/assets/6948474/5377770/0ae0796a-80c0-11e4-9eb4-3725a8094c43.png)

**Comment by WenchaoD** [comment]
fixed， 拉长，这个还需要marquee不？

**Comment by rexpie** [comment]
好像加个也可以，我看需要我就自己安上就行。closed
