### ISSUE TITLE
注册页面增加“用户协议”勾选项

### ISSUE THREAD

**Issue by rexpie** [rexpie/catchup-gui#46]
用户协议可在http://www.rexpie.net/chatime/misc/showAgreement 找到。可以直接复制到客户端，不需要特地去服务器拿一次。不同意不让注册，弹框“同意用户许可之后就可以注册啦”
UI控件可以参照：
![image](https://cloud.githubusercontent.com/assets/6948474/5427750/faadea90-83e5-11e4-8c8d-5a895817d62b.png)
勾选框个人觉得不错，需要的话我给你P一个。
注意下方其实有两个透明背景的白色图片。
![image](https://cloud.githubusercontent.com/assets/6948474/5427859/0e4fc39e-83ea-11e4-8cc0-f67462914591.png)
![image](https://cloud.githubusercontent.com/assets/6948474/5427860/113fa2fe-83ea-11e4-837e-770456278916.png)

**Comment by WenchaoD** [comment]
done
