### ISSUE TITLE
标签页，三页不同预设值：

### ISSUE THREAD

**Issue by rexpie** [rexpie/catchup-gui#50]
第一页：
"完美主义",
"职场白领",
"效率第一",
"中产阶级",
"打工战士",
"北上广漂",
"甲方是抖S",
"长期出差",
"奋斗ing",
"莘莘学子",
"IT男",
"程序媛",
"金融男",
"金融女",
"创投客",
"还贷鸭梨大"

第二页：
"白羊座",
"金牛座",
"双子座",
"巨蟹座",
"狮子座",
"处女座",
"天秤座",
"天蝎座",
"射手座",
"摩羯座",
"水瓶座",
"双鱼座",
"求交往",
"炒股达人",
"空中飞人"
第三页：
"文艺青年",
"购物狂",
"K歌之王",
"摄影爱好者",
"旅行家",
"电影控",
"追剧小能手",
"韩剧控",
"女汉子",
"人艰不拆",
"吃货",
"阿宅",
"萌妹子",
"型男",
"专业吐槽",
"_(:з”∠)_"

**Comment by WenchaoD** [comment]
done
