### ISSUE TITLE
首页点击管理约会报错

### ISSUE THREAD

**Issue by rexpie** [rexpie/catchup-gui#61]
![image](https://cloud.githubusercontent.com/assets/6948474/5560613/4f09df0c-8dd4-11e4-9855-c6cb34d46397.png)

多个main storyboard名称引用需要增加i5版和i6版支持
![image](https://cloud.githubusercontent.com/assets/6948474/5560623/a2dcee12-8dd4-11e4-8d3d-2a4d0f48ecac.png)

**Comment by WenchaoD** [comment]
done
