### ISSUE TITLE
名片认证流程

### ISSUE THREAD

**Issue by rexpie** [rexpie/catchup-gui#62]
1. 名片认证状态：未认证和已经认证。未认证状态包含已经上传并等待审核的状态。同时如果在未认证状态可以上传多次名片图片，状态仍然是未认证状态。
2. 如果名片未认证，在个人详情点击名片按钮，弹窗提问“是否上传名片并公开名片图片？”。选择确定的话，就调用图片上传接口。名片图片大小：高或者宽最大1280，按比例缩放。
   上传接口addBizcard(@RequestParam(required = true) Long id,
           @RequestParam(required = true) String token,
           @RequestBody(required = true) MultipartFile file) 
   获取接口getBizcard(@RequestParam(required = true) Long id,
           @RequestParam(required = true) String token,
           @RequestParam(required = false) Long target,
           @RequestParam(required = false) Long isThumb
3. 上传完毕之后回到个人详情页面。
4. 如果名片状态显示“已认证”，点击名片按钮进入名片查看/编辑界面。此界面和相册类似。功能包括：
   
   4.1 只包含单一图片，点击放大
   
   4.2 有一个修改按钮，点击后弹窗“是否修改名片图片？如果修改会需要重新被认证”。修改按钮图标可以借用个人信息修改按钮图标
   
   4.3 没有增加和删除按钮

认证部分属于后端行为，在前端没有表现。可能会有系统消息，通过消息系统发送，不需要进行修改。

**Comment by WenchaoD** [comment]
done
