### ISSUE TITLE
发起约会主题形式变更

### ISSUE THREAD

**Issue by rexpie** [rexpie/catchup-gui#64]
发起约会界面，主题输入框改为button，placeholder text内容和颜色均为原先输入框的。
button大小和原先的输入框一致。
button最右侧可以使用一个">"icon标记有子页面。">"标记可以从我的设置页面素材借用。">"标记竖直方向居中。
子页面布局和大众点评店铺搜索类似。最上方是自由输入框，也需要应对多行显示（方法不限，输入框可以是多行）。下方使用列表，提供快速选择。
固定内容如下：
犯困，一起买杯咖啡吧  
饭搭子已丢，求带走
加班狗，夜宵否  
烟瘾已犯，楼下聊聊天抽抽烟
买零食去，呼唤吃货
发现一款不错的蛋糕，一起分享
想认识金融圈的朋友
想找行家聊聊创业项目
想找人聊聊银行业务 
腰坐断了，求一起下楼散步
想吃小龙虾，下班就去！

**Comment by rexpie** [comment]
犯困，一起买杯咖啡吧              
饭搭子已丢，求带走
想认识金融圈的朋友
加班狗，夜宵否              
烟瘾已犯，下楼买烟否
买零食去，呼唤吃货
想找人聊聊银行业务 
发现一款不错的蛋糕，一起分享
想找行家聊聊创业项目
腰坐断了，求一起下楼散步
想吃小龙虾，下班就去！
打德州，打德州，打德州！

**Comment by WenchaoD** [comment]
finish
