### ISSUE TITLE
部分控件留有英文，需要统一

### ISSUE THREAD

**Issue by rexpie** [rexpie/catchup-gui#67]
![image](https://cloud.githubusercontent.com/assets/6948474/5664279/32877d66-978a-11e4-868c-9791e77ad270.png)
![image](https://cloud.githubusercontent.com/assets/6948474/5664281/371cbd96-978a-11e4-87c7-7c80aa53907c.png)
![image](https://cloud.githubusercontent.com/assets/6948474/5664285/3c7117f6-978a-11e4-9a6f-c74d0b879dbd.png)
![image](https://cloud.githubusercontent.com/assets/6948474/5664290/423e9e74-978a-11e4-9275-d37cd8ceb8d9.png)
![image](https://cloud.githubusercontent.com/assets/6948474/5664292/46c44066-978a-11e4-99b0-5e5bf9e8bc6f.png)

**Comment by WenchaoD** [comment]
因为控件使用系统的Locale，你的系统地区选择的是美国才会是英文
