### ISSUE TITLE
首页转轮无法翻页，点击右边按钮无反应，拉动转轮报错

### ISSUE THREAD

**Issue by rexpie** [rexpie/catchup-gui#68]
![image](https://cloud.githubusercontent.com/assets/6948474/5664723/745152a0-978d-11e4-90ae-617911e08794.png)
![image](https://cloud.githubusercontent.com/assets/6948474/5664751/953a15e2-978d-11e4-93fa-004a7e35c715.png)

**Comment by WenchaoD** [comment]
done
